{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: {{ include "director.fullname" . }}
  labels:
    {{- include "director.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.gatewayClassName }}
      kind: Gateway
  hostnames:
    {{- range .Values.gateway.hosts }}
    - {{ .host | quote }}
    {{- end }}
  rules:
    - matches:
        {{- range .Values.gateway.hosts }}
        - path:
            type: PathPrefix
            value: {{ .path }}
        {{- end }}
      backendRefs:
        - name: {{ include "director.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
