{{- if not .Values.config.valkey.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "director.fullname" . }}-config
  labels:
    {{- include "director.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.config.valkey.password | b64enc | quote }}
{{- end }}
